name: Final Task - Apache HttpClient Tests
on: workflow_dispatch

jobs: 
  run_tests_job: 
    runs-on: ubuntu-latest 
    
    steps:
      - name: Deploy API image
        run: |
              docker pull coherentsolutions/rest-training:2.0
              docker run -d -p 4044:8082 coherentsolutions/rest-training:2.0     
              
      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0  
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2
          
      - name: Checkot code
        uses: actions/checkout@v3

      - name: Build
        run: mvn --batch-mode -DskipTests package

      - name: Run Tests
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test
        
      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: https://github.com/nastyakolosovskaya/REST-API-Testing-Final-Task.git
          path: https://github.com/nastyakolosovskaya/REST-API-Testing-Final-Task.git

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: build/allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: https://github.com/nastyakolosovskaya/REST-API-Testing-Final-Task.git
          publish_dir: allure-history
